services:
  postgres:
    image: postgres:15-alpine
    container_name: scalar_money_bot_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-liquidation_bot}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user}"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: